-- Billing Services Seed Data (NGN - Nigerian Naira)
-- Run: mysql carenix_clinic -u carenix_user -p < backend/seeds/billing-services.sql
-- Or integrated in init-db.js

INSERT INTO billing_services (service_name, description, category, unit_price, is_active) VALUES
-- General Services
('Registration Fee', 'Initial patient registration', 'General Services', 5000, 1),
('Bed Space (Basic)', 'Standard bed space', 'General Services', 80000, 1),
('Bed Space (Inverter AC)', 'Air-conditioned bed space', 'General Services', 120000, 1),
('Bed Space (VIP)', 'VIP/private room', 'General Services', 150000, 1),
('Consumables per Night', 'Daily consumables', 'General Services', 3000, 1),
('Nursing Fee per Night', 'Nursing care per night', 'General Services', 10000, 1),
('Doctors Fee per Night', 'Doctor visit per night', 'General Services', 10000, 1),
('Consultation - Urologist', 'Urology specialist', 'General Services', 40000, 1),
('Consultation - Neurosurgery', 'Neurosurgery specialist', 'General Services', 40000, 1),
('Consultation - Plastic Surgery', 'Plastic surgery specialist', 'General Services', 40000, 1),
('Consultation - Paediatric Surgeon', 'Pediatric surgery', 'General Services', 30000, 1),
('Consultation - Paediatrician', 'Pediatric medicine', 'General Services', 25000, 1),
('Consultation - Medical Officer', 'General medical officer', 'General Services', 10000, 1),
('Oxygen per Hour', 'Oxygen therapy', 'General Services', 5000, 1),

-- Wound Dressing (General Services)
('Wound Dressing - Small', 'Small wound dressing', 'General Services', 3500, 1),
('Wound Dressing - Big', 'Large wound dressing', 'General Services', 5000, 1),
('Wound Dressing - Very Big', 'Very large wound dressing', 'General Services', 10000, 1),

-- Endoscopy
('Endoscopy - Upper GI (Standard)', 'Upper GI endoscopy standard', 'Endoscopy', 180000, 1),
('Endoscopy - Upper GI (+ Anaesthesia)', 'Upper GI with anaesthesia', 'Endoscopy', 280000, 1),
('Endoscopy - Upper GI (Seropositive)', 'Upper GI seropositive', 'Endoscopy', 200000, 1),
('Endoscopy - Upper GI (Seropositive + Anaesthesia)', 'Upper GI seropositive + anaesthesia', 'Endoscopy', 300000, 1),
('Endoscopy - Lower GI (Standard)', 'Lower GI endoscopy standard', 'Endoscopy', 220000, 1),
('Endoscopy - Lower GI (+ Anaesthesia)', 'Lower GI with anaesthesia', 'Endoscopy', 320000, 1),
('Endoscopy - Lower GI (Seropositive)', 'Lower GI seropositive', 'Endoscopy', 250000, 1),
('Endoscopy - Lower GI (Seropositive + Anaesthesia)', 'Lower GI seropositive + anaesthesia', 'Endoscopy', 350000, 1),

-- Surgery (Theater)
('Theater Use (1st Hour)', 'First hour of theater', 'Surgery', 100000, 1),
('Theater Use (Subsequent Hour)', 'Each additional hour', 'Surgery', 70000, 1),
('Theater Consumables - Minor', 'Minor procedure consumables', 'Surgery', 40000, 1),
('Theater Consumables - Intermediate', 'Intermediate consumables', 'Surgery', 70000, 1),
('Theater Consumables - Major', 'Major surgery consumables', 'Surgery', 120000, 1),

-- Surgery (Procedures)
('Insertion of Inter-Gastric Balloon', 'Gastric balloon insertion procedure', 'Surgery', 450000, 1),
('PEG Tube Insertion', 'Percutaneous endoscopic gastrostomy', 'Surgery', 450000, 1),
('Variceal Banding', 'Esophageal variceal banding', 'Surgery', 400000, 1),
('Polypectomy (per polyp)', 'Polyp removal per polyp', 'Surgery', 40000, 1),
('Bronchoscopy', 'Bronchoscopy procedure', 'Surgery', 450000, 1),
('Laparoscopic Surgery', 'Laparoscopic surgical procedure', 'Surgery', 450000, 1),
('Cystoscopy', 'Cystoscopy procedure', 'Surgery', 450000, 1),
('TURP', 'Transurethral resection of the prostate', 'Surgery', 450000, 1),
('Trans-sphenoidal Surgery', 'Trans-sphenoidal surgical procedure', 'Surgery', 450000, 1),

-- Medical Test
('PSA', 'Prostate Specific Antigen', 'Medical Test', 16000, 1),
('B_HCG', 'Beta Human Chorionic Gonadotropin', 'Medical Test', 16000, 1),
('AFP', 'Alpha Fetoprotein', 'Medical Test', 16000, 1),
('TSH', 'Thyroid Stimulating Hormone', 'Medical Test', 16000, 1),
('FT3', 'Free Triiodothyronine', 'Medical Test', 16000, 1),
('FT4', 'Free Thyroxine', 'Medical Test', 16000, 1),
('Vitamin D', 'Vitamin D level', 'Medical Test', 22000, 1),
('CEA', 'Carcinoembryonic Antigen', 'Medical Test', 16000, 1),
('LH', 'Luteinizing Hormone', 'Medical Test', 16000, 1),
('FSH', 'Follicle Stimulating Hormone', 'Medical Test', 16000, 1),
('Prolactin', 'Prolactin level', 'Medical Test', 16000, 1),
('E2', 'Estradiol', 'Medical Test', 16000, 1),
('Progesterone', 'Progesterone level', 'Medical Test', 16000, 1),
('CRP', 'C-Reactive Protein', 'Medical Test', 16000, 1),
('HbA1c', 'Glycated Hemoglobin', 'Medical Test', 16000, 1),
('EUCR', 'Estimated Urinary Creatinine Clearance', 'Medical Test', 16000, 1),
('Electrolyte', 'Electrolyte panel', 'Medical Test', 8000, 1),
('Urea', 'Blood Urea Nitrogen', 'Medical Test', 16000, 1),
('Creatinine', 'Serum Creatinine', 'Medical Test', 16000, 1),
('Potassium', 'Serum Potassium', 'Medical Test', 4000, 1),
('Chloride', 'Serum Chloride', 'Medical Test', 4000, 1),
('Sodium', 'Serum Sodium', 'Medical Test', 4000, 1),
('Bicarbonate', 'Serum Bicarbonate', 'Medical Test', 4000, 1),
('Calcium', 'Serum Calcium', 'Medical Test', 8000, 1),
('Phosphate', 'Serum Phosphate', 'Medical Test', 16000, 1),
('Liver Function Test (LFT)', 'Full LFT panel', 'Medical Test', 16000, 1),
('AST', 'Aspartate Aminotransferase', 'Medical Test', 16000, 1),
('ALP', 'Alkaline Phosphatase', 'Medical Test', 16000, 1),
('ALT', 'Alanine Aminotransferase', 'Medical Test', 16000, 1),
('Total Bilirubin', 'Total Bilirubin', 'Medical Test', 16000, 1),
('Direct Bilirubin', 'Direct Bilirubin', 'Medical Test', 16000, 1),
('Total Protein', 'Total Protein', 'Medical Test', 16000, 1),
('GGT', 'Gamma Glutamyl Transferase', 'Medical Test', 16000, 1),
('Albumin', 'Serum Albumin', 'Medical Test', 16000, 1),
('ESR', 'Erythrocyte Sedimentation Rate', 'Medical Test', 16000, 1),
('Fasting Lipid Profile (FLP)', 'Full lipid panel', 'Medical Test', 16000, 1),
('Total Cholesterol', 'Total Cholesterol', 'Medical Test', 16000, 1),
('HDL', 'High Density Lipoprotein', 'Medical Test', 16000, 1),
('LDL', 'Low Density Lipoprotein', 'Medical Test', 16000, 1),
('Triglyceride', 'Triglycerides', 'Medical Test', 16000, 1),
('Uric Acid', 'Serum Uric Acid', 'Medical Test', 16000, 1),
('Fasting Glucose Test (FBS)', 'Fasting Blood Sugar', 'Medical Test', 16000, 1),
('Random Glucose (RBS)', 'Random Blood Sugar', 'Medical Test', 16000, 1),
('2HPP', '2 Hour Post Prandial', 'Medical Test', 16000, 1),
('OGTT', 'Oral Glucose Tolerance Test', 'Medical Test', 16000, 1),
('Insulin Random', 'Random Insulin', 'Medical Test', 16000, 1),
('Insulin Fasting', 'Fasting Insulin', 'Medical Test', 16000, 1),
('Vitamin B12', 'Vitamin B12 level', 'Medical Test', 16000, 1),
('CA 12.5', 'Cancer Antigen 12.5', 'Medical Test', 16000, 1),
('CA 15.3', 'Cancer Antigen 15.3', 'Medical Test', 16000, 1),
('CA 19.9', 'Cancer Antigen 19.9', 'Medical Test', 16000, 1),
('Coombs Test Direct', 'Direct Coombs Test', 'Medical Test', 16000, 1),
('Coombs Test Indirect', 'Indirect Coombs Test', 'Medical Test', 16000, 1),
('Full Blood Count', 'FBC', 'Medical Test', 8500, 1),
('Peripheral Blood Film', 'Blood film microscopy', 'Medical Test', 16000, 1),
('PCV', 'Packed Cell Volume', 'Medical Test', 8500, 1),
('Reticulocyte Count', 'Reticulocytes', 'Medical Test', 16000, 1),
('G6PD Quantitative', 'G6PD Enzyme Assay', 'Medical Test', 16000, 1),
('Haemoglobin', 'Hb Electrophoresis', 'Medical Test', 16000, 1),
('HIV 1 & 2', 'HIV Screening', 'Medical Test', 16000, 1),
('Hepatitis B', 'HBsAg', 'Medical Test', 16000, 1),
('Hepatitis C', 'Anti-HCV', 'Medical Test', 16000, 1),
('Hepatitis A', 'Anti-HAV IgM', 'Medical Test', 16000, 1),
('VDRL', 'Syphilis screening', 'Medical Test', 16000, 1),
('Hepatitis B Viral Load', 'HBV DNA PCR', 'Medical Test', 16000, 1),
('Hepatitis C Viral Load', 'HCV RNA PCR', 'Medical Test', 16000, 1),
('H. Pylori Serum', 'H. pylori IgG', 'Medical Test', 16000, 1),
('TORCH Panel (Qualitative)', 'TORCH screen (Qualitative)', 'Medical Test', 16000, 1),
('TORCH Panel (Quantitative)', 'TORCH screen (Quantitative)', 'Medical Test', 16000, 1),
('Blood Culture Aerobic', 'Aerobic blood culture', 'Medical Test', 16000, 1),
('Blood Culture Anaerobic', 'Anaerobic blood culture', 'Medical Test', 16000, 1),
('Blood Group', 'ABO & Rh typing', 'Medical Test', 16000, 1),
('Genotype', 'Hb genotype', 'Medical Test', 16000, 1),
('HB Qualification (HPLC)', 'Hb variants by HPLC', 'Medical Test', 16000, 1),
('Urinalysis', 'Routine urine microscopy/chemistry', 'Medical Test', 16000, 1),
('Pregnancy Test Blood', 'Beta-hCG quantitative', 'Medical Test', 16000, 1),
('Malaria', 'Malaria parasite microscopy', 'Medical Test', 16000, 1),
('Widal', 'Widal test for typhoid', 'Medical Test', 16000, 1);

SELECT CONCAT('Seeding complete: ', COUNT(*), ' services inserted') AS message FROM billing_services;

